name: vipm
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs
  - asn1crypto
  - attrs
  - black
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cpuonly
  - cryptography
  - cycler
  - dbus
  - entrypoints
  - expat
  - flake8
  - fontconfig
  - freetype
  - future
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - joblib
  - jpeg
  - kiwisolver
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - matplotlib
  - matplotlib-base
  - mccabe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - pycodestyle
  - pycparser
  - pyflakes
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python-telegram-bot
  - pytorch
  - pytz
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - toml
  - torchvision
  - tornado
  - tqdm
  - ujson
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd

